CREATE DATABASE USER_SYSTEM;

USE USER_SYSTEM;

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    STUDENT_ID VARCHAR(20),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE,
    CAMPUS ENUM('North Campus', 'Central Campus', 'South Campus'),
    PASSWORD VARCHAR(255)
);